services:
  web:
      image: alexgravx/prisonner-web:latest
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prisoner-web.rule=Host(`prisoner.alexgravx.com`)"
        - "traefik.http.routers.prisoner-web.entrypoints=websecure"
        - "traefik.http.routers.prisoner-web.tls.certresolver=letsencrypt"
        - "traefik.http.services.prisoner-web.loadbalancer.server.port=3000"
      networks:
      - traefik

  api:
    image: alexgravx/prisonner-api:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prisoner-api.rule=Host(`prisoner.alexgravx.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.prisoner-api.entrypoints=websecure"
      - "traefik.http.routers.prisoner-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.prisoner-api.loadbalancer.server.port=8000"
    networks:
      - traefik

networks:
  traefik:
    external: true
